FROM python:3.13.7-alpine3.22
RUN addgroup -S app && adduser -S -G app -u 10001 app
WORKDIR /app
COPY cmd/canary-store/main.py /app/main.py
USER 10001:10001
EXPOSE 8080
ENTRYPOINT ["python3", "/app/main.py"]
